### ISSUE TITLE
Fullscreen transition

### ISSUE THREAD

**Issue by deckameron** [NetrisTV/ti.exoplayer#11]
Hi @drauggres 
Thank you for the module. I have been using it a lot.
This is more of a question than an issue:
Is there a way to transition between from a small view video to fullscreen and then back again?
For example change from a view to fullscreen when a change the phone orientation to landscape.
Thank you for your attention.

**Comment by drauggres** [comment]
Hi.
Don't use `fullscreen: true` when you create `VideoPlayer`. Just add it as any other view to a `Window` and use the appropriate values for `width` and` height`. Below is code sample from my app:

/app/views/player.xml
```xml
<Alloy>
  <Window id="win">
    <View id="container">
      <VideoPlayer id="player" platform="ios"/>
      <VideoPlayer id="player" platform="android" module="ru.netris.mobile.exoplayer" />
      <!--...Here was custom controls, because I have `showsControls: false` ... -->
    </View>
  </Window>
</Alloy>
```

/app/styles/player.tss
```
'#container': {
  width: Ti.UI.FILL,
  height: Ti.UI.FILL
}

"#player": {
  width: Ti.UI.FILL,
  height: Ti.UI.FILL,
  showsControls: false,
  touchEnabled: false,
  autoplay: false,
  fullscreen: false
  scalingMode: Titanium.Media.VIDEO_SCALING_ASPECT_FIT
}
```

You may also want to take a look at [Ti.ImmersiveMode](https://github.com/AppWerft/Ti.ImmersiveMode) (I'm still using [this](https://github.com/NetrisTV/ImmersiveMode) old one for the same purpose)

**Comment by deckameron** [comment]
Thank you @drauggres!
I will compile the module Ti.ImmersiveMode for Titanium SDK 9 and give it a try.
My best.
