### ISSUE TITLE
How could we enable the PictureInPicture?

### ISSUE THREAD

**Issue by danimarin** [NetrisTV/ti.exoplayer#13]
Even if I add:

`android:resizeableActivity="true" android:supportsPictureInPicture="true"`

To the main manifest activity, once I try to launch the PictureInPicture, it always says:

`Error: enterPictureInPictureMode: Current activity does not support picture-in-picture.`

It looks like somewhere, opening the TiWindow that has the player view, those attributes are lost...

Any ideas?

**Comment by drauggres** [comment]
Hi.
I never tried PiP. Can you create a sample app and upload it on github?

**Comment by drauggres** [comment]
https://github.com/appcelerator/titanium_mobile/discussions/12780

For the record, in case anyone wants to implement this in the future.

**Comment by danimarin** [comment]
Thanks drauggres, that answer worked for me ;)
