### ISSUE TITLE
Building app stuck at 'Running dexer:'

### ISSUE THREAD

**Issue by dave101** [NetrisTV/ti.exoplayer#2]
Using titanium SDK 7.1.1, when running my app with the exoplayer module installed, it does not build and gets stuck on 'Running dexer: ...', when I remove the module, it runs fine.

Eventually i get the following error:
[ERROR] Application Installer abnormal process termination. Process exit value was 1
[ERROR] :  Failed to run dexer:
[ERROR] :  
[ERROR] :  UNEXPECTED TOP-LEVEL ERROR:
[ERROR] :  java.lang.OutOfMemoryError: Java heap space
[ERROR] :  	at java.util.Arrays.copyOf(Arrays.java:3236)
[ERROR] :  	at java.io.ByteArrayOutputStream.toByteArray(ByteArrayOutputStream.java:191)
[ERROR] :  	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:279)
[ERROR] :  	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
[ERROR] :  	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
[ERROR] :  	at com.android.dx.command.dexer.Main.processOne(Main.java:679)
[ERROR] :  	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:576)
[ERROR] :  	at com.android.dx.command.dexer.Main.runMultiDex(Main.java:368)
[ERROR] :  	at com.android.dx.command.dexer.Main.runDx(Main.java:289)
[ERROR] :  	at com.android.dx.command.dexer.Main.main(Main.java:247)
[ERROR] :  	at com.android.dx.command.Main.main(Main.java:94)

**Comment by drauggres** [comment]
Hi. Try this:
`ti config android.dx.maxMemory 4096M`
`ti config android.javac.maxMemory 4096M`

**Comment by dave101** [comment]
Thanks for the quick response,
updating the dx.maxMemory to 2048M resolved the issue.

Great module by the way!
