### ISSUE TITLE
Audio only player?

### ISSUE THREAD

**Issue by AppWerft** [NetrisTV/ti.exoplayer#5]
is it possible? Whats about texts inside datastream?

**Comment by drauggres** [comment]
Hi @AppWerft.
> Audio only player? is it possible?

It is possible to start playing audio without creating video view (`surfaceType: ExoPlayer.SURFACE_TYPE_NONE`), but work in background is not implemented.

>Whats about texts inside datastream?

Don't know what exactly do you mean. You should check out [ExoPlayer documentation](https://github.com/google/ExoPlayer#documentation), if it supports what you want, we can make it work here.

**Comment by AppWerft** [comment]
`but work in background is not implemented.` what happens if the screen saver comes?

text data stream: metadata

**Comment by AppWerft** [comment]
What I have to do to add the background functionality?

**Comment by AppWerft** [comment]
The surfaceType is not part of handleCreationDict(). I don't understand how it works.

**Comment by drauggres** [comment]
> but work in background is not implemented. what happens if the screen saver comes?

Activity stopped -> player released.

> What I have to do to add the background functionality?

I would prefer not to implement background functionality in `VideoPlayer`. This should be part of `AudioPlayer` (or `MediaPlayer`) preferably with the same API as `Ti.Media` one.

About implementation read this: https://google.github.io/ExoPlayer/faqs.html#how-do-i-keep-audio-playing-when-my-app-is-backgrounded

>The surfaceType is not part of handleCreationDict(). I don't understand how it works.

https://github.com/NetrisTV/ti.exoplayer/blob/master/app/src/main/java/ru/netris/mobile/exoplayer/TiUIVideoView.java#L190
