### ISSUE TITLE
Modifying code

### ISSUE THREAD

**Issue by AppWerft** [NetrisTV/ti.exoplayer#7]
Hi,

my plan is to add the background functionality by usage foreground service. How can I edit? If I add to AxwayStudio and add org.eclipse.jdt.core.javanature to .project in root folder then it doesnt work. 

How can I open in Android Studio?

**Comment by drauggres** [comment]
Don't know much about AxwayStudio, but I think you shold open `android` directory, not root.
> How can I open in Android Studio?

Run this in terminal:
```shell
git clone git@github.com:NetrisTV/ti.exoplayer.git
cd ti.exoplayer
./gradlew tiBuild  
```

1. Run Android Studio.
2. Click "Open an existing Android Studio project"
3. Select your "ti.exoplayer" directory

You may want to change `ext.tiSDKName` and `ext.tiSDKVersion` in `build.gradle` or install Titanium SDK version specified there.
