### ISSUE TITLE
Video Only

### ISSUE THREAD

**Issue by deckameron** [NetrisTV/ti.exoplayer#8]
Is there a way to play the video only, no audio?

I tried setting the volume to 0, but turns the system media audio to 0, and not just the video.

Thank you!

**Comment by drauggres** [comment]
Hi.
From [API documentation](/NetrisTV/ti.exoplayer/blob/master/android/documentation/index.md#properties-1):

> `volume`: Ajusts volume of [`AudioManager.STREAM_MUSIC`](https://developer.android.com/reference/android/media/AudioManager.html#STREAM_MUSIC)

Also you can completely disable audio rendering with `setTrackSelectionOverride` method.

**Comment by deckameron** [comment]
Thank you @drauggres !
